<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart');

    //creo un array con gli ID dei prodotti Free Sample in carrello
    $items_id_array = array();
    $items = $cart->getQuote()->getAllItems();
    $totalItem = count($items);

    foreach($items as $item) {
        $product = $item->getProduct();
        $categories = $product->getCategoryIds();
        
        if(count($categories) > 0){
            $category = $objectManager->create('Magento\Catalog\Model\Category')->load($categories[0]);
            if(count($categories) == 1 && $category->getName() == "freesample"){
                $items_id_array[] = $item->getProductId();
                $cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
                $items_id_array["item-".$item->getProductId()] = $cartHelper->getDeletePostJson($item);
                //echo $cartHelper->getDeletePostJson($item);
            }
        }
    }
    //var_dump($items_id_array);
    //var_dump(count($items_id_array));
    //var_dump(count($items_id_array)/2);
    $freeItems = count($items_id_array)/2;

    //se nel carrello ci sono solo i prodotti Free Sample svuoto il carrello
    if($totalItem == $freeItems){
        $cartEmpty = $cart->truncate();
        $cartEmpty->saveQuote();
    }

    $max = $block->getMax();
    $import = $block->getImport();
    $total = $cart->getQuote()->getGrandTotal();
?>
<?php if($import < $total) : ?>
<div id="freesample" class="free products-grid"><h2 class="freesample-title"><?php echo __('Get three products for free'); ?></h2>
<?php
    //$categoryId = 45;        $title = 'freesample';    $collectionFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');    $collection = $collectionFactory->create()->addAttributeToFilter('name',$title)->setPageSize(1);    $categoryId = -1;        if ($collection->getSize()) {        $categoryId = $collection->getFirstItem()->getId();    }        //print_r($categoryId);        $category_id_array = array($categoryId);
    $categoryProducts = $block->getProductCollection($category_id_array); 
    $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');   
    echo "<ol class='products list items product-items'>";
    foreach ($categoryProducts as $product) {
        echo "<li class='item product product-item tile scale-anm'>";
        //print_r($product->getData());
        
        $addToCartUrl = rtrim($objectManager->get('Magento\Checkout\Helper\Cart')->getAddUrl($product), 'in_cart/1/')."/";
        //$addToCartUrl.= 'form_key/';
        //var_dump($addToCartUrl);
        
        //get product image
        $productImage = $imageBlock->getImage($product, 'category_page_list');
        echo $productImage->toHtml();
        echo "<h3 title='".$product->getName()."'>".$product->getName()."</h3>";
?>
<?php if(in_array($product->getId(), $items_id_array)) : ?>
        <?php 
            $removeData = json_decode($items_id_array["item-".$product->getId()]);
            $removeId = $removeData->data->id;
            $removeUenc = $removeData->data->uenc;
        ?>
        <div class="ck-button">  			<label>  				<input type="checkbox" name="free" value="<?php echo $product->getId(); ?>" max="<?php echo $max; ?>" url="<?php echo $addToCartUrl; ?>" removeId="<?php echo $removeId; ?>" uenc="<?php echo urlencode($removeUenc); ?>" checked ><span><?php echo __('Added');?></span>			</label>		</div>
        <!--<a href="#" class="action action-delete remove-<?php //echo $product->getId(); ?>" data-post='<?php //echo $items_id_array["item-".$product->getId()]; ?>'></a>-->
<?php else : ?>
<?php if($freeItems == $max) : ?>				<div class="ck-button">  			<label>
        		<input type="checkbox" name="free" value="<?php echo $product->getId(); ?>" max="<?php echo $max; ?>" disabled ><span><?php echo __('Add');?></span>			</label>		</div>		
<?php else : ?>		<div class="ck-button">  			<label>
        		<input class="ck-button" type="checkbox" name="free" value="<?php echo $product->getId(); ?>" max="<?php echo $max; ?>" url="<?php echo $addToCartUrl; ?>" ><span><?php echo __('Add');?></span>			</label>		</div>		
<?php endif; ?>
<?php endif; ?>
<?php
        echo "</li>";
    }
    echo "</ol>";
?>
</div>
<?php endif; ?>